# Generated by Django 5.2.7 on 2026-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_department_doctor_available_days_doctor_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('drugs', 'Drugs & Supplements'), ('library', 'Health Library'), ('research', 'Research'), ('wellbeing', 'Well-Being')], max_length=20)),
                ('summary', models.TextField()),
                ('icon', models.CharField(default='fa-solid fa-heart-pulse', max_length=50)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
