# Generated by Django 5.2.7 on 2026-04-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_healthresource_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='short_bio',
            field=models.TextField(),
        ),
    ]
